Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

# 個別にfalseや設定をする
Layout/HashAlignment:
  Exclude:
    - lib/tasks/auto_annotate_models.rake

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

# 以下はfalse
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - Gemfile
    - bin/*
    - config/puma.rb
    - config/spring.rb
    - db/schema.rb
    - db/migrate/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - submodules/zengin-code/bin/**
    - vendor/bundle/**/*
    - node_modules/**/*
