default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: eclea
  password: password

development:
  <<: *default
  database: baseball_score_development

test:
  <<: *default
  database: baseball_score_test

production:
  <<: *default
  database: baseball_score_production
  username: baseball_score
  password: <%= ENV['BASEBALL_SCORE_DATABASE_PASSWORD'] %>
